import { type RegistryEntry } from "../core/appRegistry";

const ASSETS_BASE_URL = "https://os.prozilla.dev/assets";
const ICON_BASE_URL = ASSETS_BASE_URL + "/apps/icons";
const SCREENSHOT_BASE_URL = ASSETS_BASE_URL + "/screenshots/apps";

export const DEFAULT_REGISTERED_APPS: Omit<RegistryEntry, "isInstalled">[] = [
	{
		id: "file-explorer",
		name: "Files",
		description: "Browse and manage your virtual files.",
		iconUrl: `${ICON_BASE_URL}/file-explorer.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/file-explorer-screenshot-1.png`],
		category: "Utilities & tools",
		packageName: "@prozilla-os/file-explorer",
		exportName: "fileExplorer",
	},
	{
		id: "terminal",
		name: "Commands",
		description: "A command line tool inspired by the Unix shell.",
		iconUrl: `${ICON_BASE_URL}/terminal.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/terminal-screenshot-1.png`],
		category: "Utilities & tools",
		packageName: "@prozilla-os/terminal",
		exportName: "terminal",
	},
	{
		id: "text-editor",
		name: "Notes",
		description: "Text editor for reading and writing text documents.",
		iconUrl: `${ICON_BASE_URL}/text-editor.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/text-editor-screenshot-1.png`],
		category: "Utilities & tools",
		packageName: "@prozilla-os/text-editor",
		exportName: "textEditor",
	},
	{
		id: "settings",
		name: "Settings",
		description: "Configure your settings and customize your experience.",
		iconUrl: `${ICON_BASE_URL}/settings.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/settings-screenshot-1.png`],
		category: "Personalization",
		packageName: "@prozilla-os/settings",
		exportName: "settings",
	},
	{
		id: "media-viewer",
		name: "Photos",
		iconUrl: `${ICON_BASE_URL}/media-viewer.svg`,
		category: "Photo & video",
		packageName: "@prozilla-os/media-viewer",
		exportName: "mediaViewer",
	},
	{
		id: "browser",
		name: "Browser",
		description: "Browse the internet.",
		iconUrl: `${ICON_BASE_URL}/browser.svg`,
		category: "Utilities & tools",
		packageName: "@prozilla-os/browser",
		exportName: "browser",
	},
	{
		id: "calculator",
		name: "Maths",
		description: "Simple calculator app.",
		iconUrl: `${ICON_BASE_URL}/calculator.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/calculator-screenshot-1.png`],
		category: "Utilities & tools",
		packageName: "@prozilla-os/calculator",
		exportName: "calculator",
	},
	{
		id: "wordle",
		name: "Wordle",
		description: "Guess the 5-letter word in 6 tries or less.",
		iconUrl: `${ICON_BASE_URL}/wordle.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/wordle-screenshot-1.png`],
		packageName: "@prozilla-os/wordle",
		exportName: "wordle",
	},
	{
		id: "ball-maze",
		name: "Ball Maze",
		description: "A 3D wooden ball maze game.",
		iconUrl: `${ICON_BASE_URL}/ball-maze.svg`,
		packageName: "@prozilla-os/ball-maze",
		exportName: "ballMaze",
	},
	{
		id: "minesweeper",
		name: "Minesweeper",
		description: "A Minesweeper game.",
		iconUrl: `${ICON_BASE_URL}/minesweeper.svg`,
		screenshots: [`${SCREENSHOT_BASE_URL}/minesweeper-screenshot-1.png`],
		packageName: "@prozilla-os/minesweeper",
		exportName: "minesweeper",
	},
	{
		id: "logic-sim",
		name: "Logic Sim",
		description: "Create digital logic circuits using the online simulator.",
		iconUrl: `${ICON_BASE_URL}/logic-sim.svg`,
		category: "Education",
		packageName: "@prozilla-os/logic-sim",
		exportName: "logicSim",
	},
];
