export const APP_CATEGORIES = [
	"Business",
	"Developer tools",
	"Education",
	"Entertainment",
	"Food & dining",
	"Health & fitness",
	"Kids & family",
	"Lifestyle",
	"Media",
	"Medical",
	"Multimedia design",
	"Music",
	"Navigation & maps",
	"News & weather",
	"Personal finance",
	"Personalization",
	"Photo & video",
	"Productivity",
	"Security",
	"Shopping",
	"Social",
	"Sports",
	"Travel",
	"Utilities & tools",
] as const;