packages:
  - packages/*
  - packages/apps/*
  - demo
  - docs
  - examples/*
allowBuilds:
  "@swc/core": true
  "esbuild": true
overrides:
  "prozilla-os": "workspace:*"
  "@prozilla-os/core": "workspace:*"
  "@prozilla-os/shared": "workspace:*"
  "@prozilla-os/skins": "workspace:*"
  "@prozilla-os/dev-tools": "workspace:*"
