import { randomFromArray } from "../../../_utils/array.utils.js";
import Command from "../command.js";

/**
 * Source: https://github.com/shlomif/fortune-mod/blob/master/fortune-mod/datfiles/fortunes
 */
const FORTUNES = [
	"A day for firm decisions!!!!! Or is it?",
	"Just to have it is enough.",
	"Keep emotionally active. Cater to your favorite neurosis.",
	"Keep it short for pithy sake.",
	"Lady Luck brings added income today. Lady friend takes it away tonight.",
	"Learn to pause -- or nothing worthwhile can catch up to you.",
	"Let me put it this way: today is going to be a learning experience.",
	"Life is to you a dashing and bold adventure.",
	"\"Life, loathe it or ignore it, you can't like it.\"\n\n 		-- Marvin, \"Hitchhiker's Guide to the Galaxy\"",
	"Live in a world of your own, but always welcome visitors.",
	"Living your life is a task so difficult, it has never been attempted before.",
	"Long life is in store for you.",
	"Look afar and see the end from the beginning.",
	"Love is in the offing. Be affectionate to one who adores you.",
	"Make a wish, it might come true.",
	"Many changes of mind and mood; do not hesitate too long.",
	"Never be led astray onto the path of virtue.",
	"Never commit yourself!  Let someone else commit you.",
	"Never give an inch!",
	"Never look up when dragons fly overhead.",
	"Never reveal your best argument.",
	"Next Friday will not be your lucky day. As a matter of fact, you don't have a lucky day this year.",
	"Of course you have a purpose -- to find a purpose.",
	"People are beginning to notice you. Try dressing before you leave the house.",
	"Perfect day for scrubbing the floor and other exciting things.",
	"Questionable day.\n\nAsk somebody something.",
	"Reply hazy, ask again later.",
	"Save energy: be apathetic.",
	"Ships are safe in harbor, but they were never meant to stay there.",
	"Slow day. Practice crawling.",
	"Snow Day -- stay home.",
	"So this is it. We're going to die.",
	"So you're back... about time...",
	"Someone is speaking well of you.",
	"Someone is speaking well of you.\n\nHow unusual!",
	"Someone whom you reject today, will reject you tomorrow.",
	"Stay away from flying saucers today.",
	"Stay away from hurricanes for a while.",
	"Stay the curse.",
	"That secret you've been guarding, isn't.",
	"The time is right to make new friends.",
	"The whole world is a tuxedo and you are a pair of brown shoes.\n\n		-- George Gobel",
	"There is a 20% chance of tomorrow.",
	"There is a fly on your nose.",
	"There was a phone call for you.",
	"You're not my type. For that matter, you're not even my species!!!",
	"You're ugly and your mother dresses you funny.",
	"You're working under a slight handicap. You happen to be human.",
	"You've been leading a dog's life. Stay off the furniture.",
	"Your aim is high and to the right.",
	"Your aims are high, and you are capable of much.",
	"Your analyst has you mixed up with another patient. Don't believe a thing he tells you.",
	"Your best consolation is the hope that the things you failed to get weren't really worth having.",
	"Your boss climbed the corporate ladder, wrong by wrong.",
	"Your boss is a few sandwiches short of a picnic.",
	"Your boyfriend takes chocolate from strangers.",
	"Your business will assume vast proportions.",
	"Your business will go through a period of considerable expansion.",
	"Your depth of comprehension may tend to make you lax in worldly ways.",
	"Your domestic life may be harmonious.",
	"Your fly might be open (but don't check it just now).",
	"Your goose is cooked. (Your current chick is burned up too!)",
	"Your heart is pure, and your mind clear, and your soul devout.",
	"Your ignorance cramps my conversation.",
	"Your life would be very empty if you had nothing to regret.",
	"Your love life will be happy and harmonious.",
	"Your love life will be... interesting.",
	"Your lover will never wish to leave you.",
	"Your lucky color has faded.",
	"Your lucky number has been disconnected.",
	"Your lucky number is 3552664958674928. Watch for it everywhere.",
	"Your mode of life will be changed for the better because of good news soon.",
	"Your mode of life will be changed for the better because of new developments.",
	"Your motives for doing whatever good deed you may have in mind will be misinterpreted by somebody.",
	"Your nature demands love and your happiness depends on it.",
	"Your object is to save the world, while still leading a pleasant life.",
	"Your own qualities will help prevent your advancement in the world.",
	"Your present plans will be successful.",
	"Your reasoning is excellent -- it's only your basic assumptions that are wrong.",
	"Your reasoning powers are good, and you are a fairly good planner.",
	"Your sister swims out to meet troop ships.",
	"Your society will be sought by people of taste and refinement.",
	"Your step will soil many countries.",
	"Your supervisor is thinking about you.",
	"Your talents will be recognized and suitably rewarded.",
	"Your temporary financial embarrassment will be relieved in a surprising manner.",
	"Your true value depends entirely on what you are compared with.",
];

export const fortune = new Command("fortune")
	.setManual({
		purpose: "Tell fortune"
	})
	.setExecute(() => {
		return randomFromArray(FORTUNES);
	});