name: Deploy website

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(gh release view --json tagName --template '{{.tagName}}' || git tag -l "v*" --sort=-v:refname | head -n 1)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Found tag: $LATEST_TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout latest release
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
          path: latest-release

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Install release dependencies
        run: cd latest-release && pnpm install --frozen-lockfile

      - name: Build release packages
        run: cd latest-release && pnpm run packages:build

      - name: Build packages
        run: pnpm run build
        env:
          RELEASE_PATH: ${{ github.workspace }}/latest-release

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Deploy site
        run: pnpm run deploy